version: "3"

vars:
  ROOT: "."
  WEB_DIR: "apps/web"
  FUNCTIONS_DIR: "apps/functions"
  SHARED_DIR: "packages/shared"
  PROJECT_ID: "kototsute"
  EMULATOR_DATA_DIR: "tmp/emulators"

includes: {}

silent: false


tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  install:
    desc: "Install root deps with pnpm"
    cmds:
      - pnpm install

  install:all:
    desc: "Install root and functions deps"
    cmds:
      - pnpm install
      - pnpm -C {{.FUNCTIONS_DIR}} install

  dev:
    desc: "Run Vite dev server with Firebase emulators (core)"
    cmds:
      - task -p firebase:emulate dev:app functions:watch

  dev:app:
    desc: "Run Vite dev server"
    cmds:
      - pnpm -C {{.WEB_DIR}} dev -- --open

  build:
    desc: "Build shared, functions, and web"
    cmds:
      - pnpm -C {{.SHARED_DIR}} build && pnpm -C {{.FUNCTIONS_DIR}} build && pnpm -C {{.WEB_DIR}} build

  preview:
    desc: "Preview production build"
    cmds:
      - pnpm -C {{.WEB_DIR}} preview

  functions:build:
    desc: "Build shared + Firebase Functions"
    cmds:
      - pnpm -C {{.SHARED_DIR}} build && pnpm -C {{.FUNCTIONS_DIR}} build

  functions:watch:
    desc: "Watch Firebase Functions (tsc -w)"
    cmds:
      - pnpm -C {{.FUNCTIONS_DIR}} watch

  firebase:emulate:
    desc: "Start emulators (core)"
    cmds:
      - mkdir -p {{.EMULATOR_DATA_DIR}}
      - firebase emulators:start --project {{.PROJECT_ID}} --only functions,auth,firestore,storage --import {{.EMULATOR_DATA_DIR}} --export-on-exit {{.EMULATOR_DATA_DIR}}

  firebase:emulators:
    desc: "Start Firebase emulators (all)"
    cmds:
      - mkdir -p {{.EMULATOR_DATA_DIR}}
      - firebase emulators:start --project {{.PROJECT_ID}} --import {{.EMULATOR_DATA_DIR}} --export-on-exit {{.EMULATOR_DATA_DIR}}

  clean:
    desc: "Remove build outputs"
    cmds:
      - rm -rf {{.WEB_DIR}}/dist
      - rm -rf {{.FUNCTIONS_DIR}}/lib
